import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * A reference list of countries, so a student profile is filled by picking
 * from a list rather than typing free text that then has to be normalised
 * before it is useful (nationality, address, intended destination all landed
 * as bare `text` columns in earlier migrations for exactly that reason).
 *
 * `isDestination` marks the ~20 countries the catalogue actually has
 * universities in (the same set `scripts/import-ror.ts` imports from) — the
 * "where do you want to study" dropdown filters to these, while nationality
 * and address use the full list.
 */
export class Countries1757001200000 implements MigrationInterface {
  name = 'Countries1757001200000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "countries" (
        "code" varchar(2) PRIMARY KEY,
        "name" text NOT NULL,
        "isDestination" boolean NOT NULL DEFAULT false
      );
    `);

    await queryRunner.query(`
      INSERT INTO "countries" ("code", "name", "isDestination") VALUES
        ('AF', 'Afghanistan', false),
        ('AL', 'Albania', false),
        ('DZ', 'Algeria', false),
        ('AD', 'Andorra', false),
        ('AO', 'Angola', false),
        ('AG', 'Antigua and Barbuda', false),
        ('AR', 'Argentina', false),
        ('AM', 'Armenia', false),
        ('AU', 'Australia', true),
        ('AT', 'Austria', false),
        ('AZ', 'Azerbaijan', false),
        ('BS', 'Bahamas', false),
        ('BH', 'Bahrain', false),
        ('BD', 'Bangladesh', false),
        ('BB', 'Barbados', false),
        ('BY', 'Belarus', false),
        ('BE', 'Belgium', false),
        ('BZ', 'Belize', false),
        ('BJ', 'Benin', false),
        ('BT', 'Bhutan', false),
        ('BO', 'Bolivia', false),
        ('BA', 'Bosnia and Herzegovina', false),
        ('BW', 'Botswana', false),
        ('BR', 'Brazil', false),
        ('BN', 'Brunei', false),
        ('BG', 'Bulgaria', false),
        ('BF', 'Burkina Faso', false),
        ('BI', 'Burundi', false),
        ('CV', 'Cabo Verde', false),
        ('KH', 'Cambodia', false),
        ('CM', 'Cameroon', false),
        ('CA', 'Canada', true),
        ('CF', 'Central African Republic', false),
        ('TD', 'Chad', false),
        ('CL', 'Chile', false),
        ('CN', 'China', false),
        ('CO', 'Colombia', false),
        ('KM', 'Comoros', false),
        ('CG', 'Congo', false),
        ('CD', 'Congo (DRC)', false),
        ('CR', 'Costa Rica', false),
        ('CI', 'Cote d''Ivoire', false),
        ('HR', 'Croatia', false),
        ('CU', 'Cuba', false),
        ('CY', 'Cyprus', true),
        ('CZ', 'Czechia', false),
        ('DK', 'Denmark', false),
        ('DJ', 'Djibouti', false),
        ('DM', 'Dominica', false),
        ('DO', 'Dominican Republic', false),
        ('EC', 'Ecuador', false),
        ('EG', 'Egypt', false),
        ('SV', 'El Salvador', false),
        ('GQ', 'Equatorial Guinea', false),
        ('ER', 'Eritrea', false),
        ('EE', 'Estonia', false),
        ('SZ', 'Eswatini', false),
        ('ET', 'Ethiopia', false),
        ('FJ', 'Fiji', false),
        ('FI', 'Finland', false),
        ('FR', 'France', true),
        ('GA', 'Gabon', false),
        ('GM', 'Gambia', false),
        ('GE', 'Georgia', false),
        ('DE', 'Germany', true),
        ('GH', 'Ghana', false),
        ('GR', 'Greece', false),
        ('GD', 'Grenada', true),
        ('GT', 'Guatemala', false),
        ('GN', 'Guinea', false),
        ('GW', 'Guinea-Bissau', false),
        ('GY', 'Guyana', false),
        ('HT', 'Haiti', false),
        ('HN', 'Honduras', false),
        ('HK', 'Hong Kong', false),
        ('HU', 'Hungary', true),
        ('IS', 'Iceland', false),
        ('IN', 'India', false),
        ('ID', 'Indonesia', false),
        ('IR', 'Iran', false),
        ('IQ', 'Iraq', false),
        ('IE', 'Ireland', true),
        ('IL', 'Israel', false),
        ('IT', 'Italy', true),
        ('JM', 'Jamaica', false),
        ('JP', 'Japan', false),
        ('JO', 'Jordan', false),
        ('KZ', 'Kazakhstan', false),
        ('KE', 'Kenya', false),
        ('KI', 'Kiribati', false),
        ('KW', 'Kuwait', false),
        ('KG', 'Kyrgyzstan', false),
        ('LA', 'Laos', false),
        ('LV', 'Latvia', false),
        ('LB', 'Lebanon', false),
        ('LS', 'Lesotho', false),
        ('LR', 'Liberia', false),
        ('LY', 'Libya', false),
        ('LI', 'Liechtenstein', false),
        ('LT', 'Lithuania', false),
        ('LU', 'Luxembourg', false),
        ('MO', 'Macao', false),
        ('MG', 'Madagascar', false),
        ('MW', 'Malawi', false),
        ('MY', 'Malaysia', true),
        ('MV', 'Maldives', false),
        ('ML', 'Mali', false),
        ('MT', 'Malta', true),
        ('MH', 'Marshall Islands', false),
        ('MR', 'Mauritania', false),
        ('MU', 'Mauritius', true),
        ('MX', 'Mexico', false),
        ('FM', 'Micronesia', false),
        ('MD', 'Moldova', false),
        ('MC', 'Monaco', false),
        ('MN', 'Mongolia', false),
        ('ME', 'Montenegro', false),
        ('MA', 'Morocco', false),
        ('MZ', 'Mozambique', false),
        ('MM', 'Myanmar', false),
        ('NA', 'Namibia', false),
        ('NR', 'Nauru', false),
        ('NP', 'Nepal', false),
        ('NL', 'Netherlands', true),
        ('NZ', 'New Zealand', true),
        ('NI', 'Nicaragua', false),
        ('NE', 'Niger', false),
        ('NG', 'Nigeria', false),
        ('KP', 'North Korea', false),
        ('MK', 'North Macedonia', false),
        ('NO', 'Norway', false),
        ('OM', 'Oman', false),
        ('PK', 'Pakistan', false),
        ('PW', 'Palau', false),
        ('PS', 'Palestine', false),
        ('PA', 'Panama', false),
        ('PG', 'Papua New Guinea', false),
        ('PY', 'Paraguay', false),
        ('PE', 'Peru', false),
        ('PH', 'Philippines', false),
        ('PL', 'Poland', true),
        ('PT', 'Portugal', false),
        ('QA', 'Qatar', false),
        ('RO', 'Romania', false),
        ('RU', 'Russia', false),
        ('RW', 'Rwanda', false),
        ('KN', 'Saint Kitts and Nevis', false),
        ('LC', 'Saint Lucia', false),
        ('VC', 'Saint Vincent and the Grenadines', false),
        ('WS', 'Samoa', false),
        ('SM', 'San Marino', false),
        ('ST', 'Sao Tome and Principe', false),
        ('SA', 'Saudi Arabia', false),
        ('SN', 'Senegal', false),
        ('RS', 'Serbia', false),
        ('SC', 'Seychelles', false),
        ('SL', 'Sierra Leone', false),
        ('SG', 'Singapore', false),
        ('SK', 'Slovakia', false),
        ('SI', 'Slovenia', false),
        ('SB', 'Solomon Islands', false),
        ('SO', 'Somalia', false),
        ('ZA', 'South Africa', false),
        ('KR', 'South Korea', false),
        ('SS', 'South Sudan', false),
        ('ES', 'Spain', true),
        ('LK', 'Sri Lanka', false),
        ('SD', 'Sudan', false),
        ('SR', 'Suriname', false),
        ('SE', 'Sweden', false),
        ('CH', 'Switzerland', true),
        ('SY', 'Syria', false),
        ('TW', 'Taiwan', false),
        ('TJ', 'Tajikistan', false),
        ('TZ', 'Tanzania', false),
        ('TH', 'Thailand', false),
        ('TL', 'Timor-Leste', false),
        ('TG', 'Togo', false),
        ('TO', 'Tonga', false),
        ('TT', 'Trinidad and Tobago', false),
        ('TN', 'Tunisia', false),
        ('TR', 'Turkey', false),
        ('TM', 'Turkmenistan', false),
        ('TV', 'Tuvalu', false),
        ('UG', 'Uganda', false),
        ('UA', 'Ukraine', false),
        ('AE', 'United Arab Emirates', true),
        ('GB', 'United Kingdom', true),
        ('US', 'United States', true),
        ('UY', 'Uruguay', false),
        ('UZ', 'Uzbekistan', false),
        ('VU', 'Vanuatu', false),
        ('VA', 'Vatican City', false),
        ('VE', 'Venezuela', false),
        ('VN', 'Vietnam', false),
        ('YE', 'Yemen', false),
        ('ZM', 'Zambia', false),
        ('ZW', 'Zimbabwe', false);
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE "countries";');
  }
}
