import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Flag emoji for every seeded country.
 *
 * Stored rather than computed on the fly: a flag emoji is just two
 * regional-indicator code points derived from the ISO code, so this is
 * redundant with what `flagEmoji()` in `@rakuxon/ui` already does purely in
 * the browser — but storing it here means any API consumer (a native
 * `<select>`, an email template, a future non-web client) gets the same flag
 * without reimplementing that string math.
 */
export class CountryFlags1757001300000 implements MigrationInterface {
  name = 'CountryFlags1757001300000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      ALTER TABLE "countries" ADD COLUMN "flagEmoji" text;
    `);

    await queryRunner.query(`
      UPDATE "countries" c SET "flagEmoji" = v.flag
      FROM (VALUES
        ('AF', '🇦🇫'),
        ('AL', '🇦🇱'),
        ('DZ', '🇩🇿'),
        ('AD', '🇦🇩'),
        ('AO', '🇦🇴'),
        ('AG', '🇦🇬'),
        ('AR', '🇦🇷'),
        ('AM', '🇦🇲'),
        ('AU', '🇦🇺'),
        ('AT', '🇦🇹'),
        ('AZ', '🇦🇿'),
        ('BS', '🇧🇸'),
        ('BH', '🇧🇭'),
        ('BD', '🇧🇩'),
        ('BB', '🇧🇧'),
        ('BY', '🇧🇾'),
        ('BE', '🇧🇪'),
        ('BZ', '🇧🇿'),
        ('BJ', '🇧🇯'),
        ('BT', '🇧🇹'),
        ('BO', '🇧🇴'),
        ('BA', '🇧🇦'),
        ('BW', '🇧🇼'),
        ('BR', '🇧🇷'),
        ('BN', '🇧🇳'),
        ('BG', '🇧🇬'),
        ('BF', '🇧🇫'),
        ('BI', '🇧🇮'),
        ('CV', '🇨🇻'),
        ('KH', '🇰🇭'),
        ('CM', '🇨🇲'),
        ('CA', '🇨🇦'),
        ('CF', '🇨🇫'),
        ('TD', '🇹🇩'),
        ('CL', '🇨🇱'),
        ('CN', '🇨🇳'),
        ('CO', '🇨🇴'),
        ('KM', '🇰🇲'),
        ('CG', '🇨🇬'),
        ('CD', '🇨🇩'),
        ('CR', '🇨🇷'),
        ('CI', '🇨🇮'),
        ('HR', '🇭🇷'),
        ('CU', '🇨🇺'),
        ('CY', '🇨🇾'),
        ('CZ', '🇨🇿'),
        ('DK', '🇩🇰'),
        ('DJ', '🇩🇯'),
        ('DM', '🇩🇲'),
        ('DO', '🇩🇴'),
        ('EC', '🇪🇨'),
        ('EG', '🇪🇬'),
        ('SV', '🇸🇻'),
        ('GQ', '🇬🇶'),
        ('ER', '🇪🇷'),
        ('EE', '🇪🇪'),
        ('SZ', '🇸🇿'),
        ('ET', '🇪🇹'),
        ('FJ', '🇫🇯'),
        ('FI', '🇫🇮'),
        ('FR', '🇫🇷'),
        ('GA', '🇬🇦'),
        ('GM', '🇬🇲'),
        ('GE', '🇬🇪'),
        ('DE', '🇩🇪'),
        ('GH', '🇬🇭'),
        ('GR', '🇬🇷'),
        ('GD', '🇬🇩'),
        ('GT', '🇬🇹'),
        ('GN', '🇬🇳'),
        ('GW', '🇬🇼'),
        ('GY', '🇬🇾'),
        ('HT', '🇭🇹'),
        ('HN', '🇭🇳'),
        ('HK', '🇭🇰'),
        ('HU', '🇭🇺'),
        ('IS', '🇮🇸'),
        ('IN', '🇮🇳'),
        ('ID', '🇮🇩'),
        ('IR', '🇮🇷'),
        ('IQ', '🇮🇶'),
        ('IE', '🇮🇪'),
        ('IL', '🇮🇱'),
        ('IT', '🇮🇹'),
        ('JM', '🇯🇲'),
        ('JP', '🇯🇵'),
        ('JO', '🇯🇴'),
        ('KZ', '🇰🇿'),
        ('KE', '🇰🇪'),
        ('KI', '🇰🇮'),
        ('KW', '🇰🇼'),
        ('KG', '🇰🇬'),
        ('LA', '🇱🇦'),
        ('LV', '🇱🇻'),
        ('LB', '🇱🇧'),
        ('LS', '🇱🇸'),
        ('LR', '🇱🇷'),
        ('LY', '🇱🇾'),
        ('LI', '🇱🇮'),
        ('LT', '🇱🇹'),
        ('LU', '🇱🇺'),
        ('MO', '🇲🇴'),
        ('MG', '🇲🇬'),
        ('MW', '🇲🇼'),
        ('MY', '🇲🇾'),
        ('MV', '🇲🇻'),
        ('ML', '🇲🇱'),
        ('MT', '🇲🇹'),
        ('MH', '🇲🇭'),
        ('MR', '🇲🇷'),
        ('MU', '🇲🇺'),
        ('MX', '🇲🇽'),
        ('FM', '🇫🇲'),
        ('MD', '🇲🇩'),
        ('MC', '🇲🇨'),
        ('MN', '🇲🇳'),
        ('ME', '🇲🇪'),
        ('MA', '🇲🇦'),
        ('MZ', '🇲🇿'),
        ('MM', '🇲🇲'),
        ('NA', '🇳🇦'),
        ('NR', '🇳🇷'),
        ('NP', '🇳🇵'),
        ('NL', '🇳🇱'),
        ('NZ', '🇳🇿'),
        ('NI', '🇳🇮'),
        ('NE', '🇳🇪'),
        ('NG', '🇳🇬'),
        ('KP', '🇰🇵'),
        ('MK', '🇲🇰'),
        ('NO', '🇳🇴'),
        ('OM', '🇴🇲'),
        ('PK', '🇵🇰'),
        ('PW', '🇵🇼'),
        ('PS', '🇵🇸'),
        ('PA', '🇵🇦'),
        ('PG', '🇵🇬'),
        ('PY', '🇵🇾'),
        ('PE', '🇵🇪'),
        ('PH', '🇵🇭'),
        ('PL', '🇵🇱'),
        ('PT', '🇵🇹'),
        ('QA', '🇶🇦'),
        ('RO', '🇷🇴'),
        ('RU', '🇷🇺'),
        ('RW', '🇷🇼'),
        ('KN', '🇰🇳'),
        ('LC', '🇱🇨'),
        ('VC', '🇻🇨'),
        ('WS', '🇼🇸'),
        ('SM', '🇸🇲'),
        ('ST', '🇸🇹'),
        ('SA', '🇸🇦'),
        ('SN', '🇸🇳'),
        ('RS', '🇷🇸'),
        ('SC', '🇸🇨'),
        ('SL', '🇸🇱'),
        ('SG', '🇸🇬'),
        ('SK', '🇸🇰'),
        ('SI', '🇸🇮'),
        ('SB', '🇸🇧'),
        ('SO', '🇸🇴'),
        ('ZA', '🇿🇦'),
        ('KR', '🇰🇷'),
        ('SS', '🇸🇸'),
        ('ES', '🇪🇸'),
        ('LK', '🇱🇰'),
        ('SD', '🇸🇩'),
        ('SR', '🇸🇷'),
        ('SE', '🇸🇪'),
        ('CH', '🇨🇭'),
        ('SY', '🇸🇾'),
        ('TW', '🇹🇼'),
        ('TJ', '🇹🇯'),
        ('TZ', '🇹🇿'),
        ('TH', '🇹🇭'),
        ('TL', '🇹🇱'),
        ('TG', '🇹🇬'),
        ('TO', '🇹🇴'),
        ('TT', '🇹🇹'),
        ('TN', '🇹🇳'),
        ('TR', '🇹🇷'),
        ('TM', '🇹🇲'),
        ('TV', '🇹🇻'),
        ('UG', '🇺🇬'),
        ('UA', '🇺🇦'),
        ('AE', '🇦🇪'),
        ('GB', '🇬🇧'),
        ('US', '🇺🇸'),
        ('UY', '🇺🇾'),
        ('UZ', '🇺🇿'),
        ('VU', '🇻🇺'),
        ('VA', '🇻🇦'),
        ('VE', '🇻🇪'),
        ('VN', '🇻🇳'),
        ('YE', '🇾🇪'),
        ('ZM', '🇿🇲'),
        ('ZW', '🇿🇼')
      ) AS v(code, flag)
      WHERE c.code = v.code;
    `);

    await queryRunner.query(`
      ALTER TABLE "countries" ALTER COLUMN "flagEmoji" SET NOT NULL;
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('ALTER TABLE "countries" DROP COLUMN "flagEmoji";');
  }
}
