import type { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Baseline. `pgcrypto` provides gen_random_uuid(), so primary keys are
 * generated by the database rather than the application — which matters
 * because row-level security policies compare database-side values.
 */
export class InitialExtensions1757000000000 implements MigrationInterface {
  name = 'InitialExtensions1757000000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('CREATE EXTENSION IF NOT EXISTS "pgcrypto"');
    await queryRunner.query('CREATE EXTENSION IF NOT EXISTS "citext"');
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    /* Extensions are cluster-level and other schemas may rely on them, so the
       rollback drops nothing. Reverting this migration is a no-op by design. */
    await queryRunner.query('SELECT 1');
  }
}
