#!/bin/sh
set -eu
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" --set=app_password="$DATABASE_APP_PASSWORD" <<'SQL'
CREATE ROLE rakuxon_app LOGIN PASSWORD :'app_password' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT CONNECT ON DATABASE rakuxon TO rakuxon_app;
GRANT USAGE ON SCHEMA public TO rakuxon_app;
ALTER DEFAULT PRIVILEGES FOR ROLE rakuxon_owner IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO rakuxon_app;
ALTER DEFAULT PRIVILEGES FOR ROLE rakuxon_owner IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO rakuxon_app;
SQL
